import {DashbordHeader} from '@/components/header-dashboard';
import {Sidebar} from '@/components/sidebar';
import {useUser} from '@/hooks/useUser';
import type {Metadata} from 'next';
import {redirect} from 'next/navigation';

export const metadata: Metadata = {
  title: 'Dashboard | Agendify',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await useUser();

  if (!user) {
    redirect('/dashboard');
  }

  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <Sidebar />
      <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <DashbordHeader user={user} />
        <main className="flex-1">{children}</main>
      </div>
    </div>
  );
}
