import '@/styles/globals.css';
import {Inter} from 'next/font/google';

import {Header} from '@/components/header';
import {AuroraGradient} from '@/components/ui/aurora-gradient';
import {Toaster} from '@/components/ui/toaster';
import {cn} from '@/lib/shadcn/utils';
import {ThemeProvider} from '@/providers/theme-provider';
import type {Metadata} from 'next';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen min-w-[100vw] overflow-x-hidden bg-background font-sans antialised',
          inter.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col">
            <AuroraGradient>
              <Header />
              <main className="flex-1">{children}</main>
            </AuroraGradient>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
